### PR TITLE
feat: handler, client, connection, channel, router

### PR DESCRIPTION
**Pull request by boohyunsik**
## Related Issue

resolve: #*(Write down your issue number)*

## Description

*(Write down your details)*

## Checklist

Thank you for your contribution. Before submitting this PR, please make sure:

- [ ] Test case
- [ ] End of Work

### CODE REVIEW

**Comment by AgwaB** [comment]
Do cosmos use `get` and `set` a lot? Adding `get` and `set` in a `getter` `setter` is not a convention of go!

for example,
```go
type Blockchain interface {
	getGenesis() Consensus
	getConsensus() Consensus
}
```
can be

```go
type Blockchain interface {
	genesis() Consensus
	consensus() Consensus
}
```

**Comment by junbeomlee** [comment]
The convention is correct, but because it is defined in the spec, 
we should use 
```
type Blockchain interface {
	getGenesis() Consensus
	getConsensus() Consensus
}
```

**Comment by junbeomlee** [comment]
Move all interface code to the `spec` folder

**Review by junbeomlee — APPROVED** [review]
lgtm

**Pull request merged**
